fix(sendsay-docs) add how-to-create-sms-campaign
sendsay-ru/sendsay-docs pull request #323
Opened 2024-09-17 07:49 UTC by vypolzovv

edit how-to-connect-sms

[Тикет Fibery](https://sendsay.fibery.io/%D0%90%D0%B2%D1%82%D0%BE%D1%80%D1%81%D0%BA%D0%B0%D1%8F/%D0%97%D0%B0%D0%B4%D0%B0%D1%87%D0%B8_%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%BE%D0%B2/250)

2024-09-17 08:22 UTC, Ksksksksen requested changes

2024-09-17 08:22 UTC, Ksksksksen commented on docs/other-channels/sms/how-to-connect-sms.md
> +- Выписка из ЕГРЮЛ или свидетельство о регистрации юрлица/свидетельство о регистрации ИНН;
почему здесь и в следующих двух пунктах названия документов в начале с заглавной буквы, при том что это, судя по знакам препинания, не новые предложения?

2024-09-17 08:22 UTC, Ksksksksen commented on docs/other-channels/sms/how-to-connect-sms.md
> +- Лицензионный договор, договор франшизы и т.п. (если у вас есть такой договор);
точка с запятой в конце списка предполагает, что дальше будет продолжение. так где продолжение?)

2024-09-17 08:22 UTC, Ksksksksen commented on docs/other-channels/sms/how-to-connect-sms.md
> +- документ для обоснования имени, например: договор франшизы, свидетельство о регистрации товарного знака или подтверждение прав на сайт от регистратора доменов.
просто «заранее подготовленные документы из п. 1»

2024-09-17 08:22 UTC, Ksksksksen commented on docs/other-channels/sms/how-to-connect-sms.md
> +Для каждого аккаунта у операторов мобильной связи регистрируется индивидуальное имя отправителя. Имя должно соответствовать нескольким требованиям:
само регистрируется?

2024-09-17 08:22 UTC, Ksksksksen commented on docs/other-channels/sms/how-to-create-sms-campaign.md
> +sidebar_label: 'Как отправить SMS-рассылку'
обрати внимание, что в статье «Как подключить» используется кириллица: смс, смс-рассылка. Это обосновано тем, что именно так люди ищут, чекни вордстат. Давай приведём здесь к такому же виду, но в сайдбаре оставим название на латинице.

2024-09-17 08:22 UTC, Ksksksksen commented on docs/other-channels/sms/how-to-create-sms-campaign.md
> +[Как подключить SMS](https://docs.sendsay.ru/other-channels/sms/how-to-connect-sms/)
Статья называется «Как подключить смс»

2024-09-17 08:22 UTC, Ksksksksen commented on docs/other-channels/sms/how-to-create-sms-campaign.md
> +# Как отправить SMS-рассылку
Как отправить смс-рассылку

2024-09-17 08:22 UTC, Ksksksksen commented on docs/other-channels/sms/how-to-create-sms-campaign.md
> +SMS-выпуск — это текстовое сообщение, отправленное по номеру телефона на мобильные устройства подписчиков через сеть сотовой связи.
Смс-выпуск — это...

2024-09-17 08:22 UTC, Ksksksksen commented on docs/other-channels/sms/how-to-create-sms-campaign.md
> +![How to limit audience](/img/other-channels/sms\how-to-create-sms-campaign/how-to-limit-audience.png)
картинка меньше ширины статьи, давай добавим её другим способом и центрируем

2024-09-17 08:22 UTC, Ksksksksen commented on docs/other-channels/sms/how-to-create-sms-campaign.md
> +Современные устройства собирают в одно сообщение до 5 смс. Это значит, что для разбитого на части сообщения также нужно следить за лимитом символов:
давай переформулируем второе предложение в контексте максимального количества символов в одном выпуске, — чтобы не создавалось впечатление, будто нужно самостоятельно за чем-то следить

2024-09-17 08:22 UTC, Ksksksksen commented on docs/other-channels/sms/how-to-create-sms-campaign.md
> +С помощью этого пункта можно настроить передачу дополнительных данных из анкеты подписчика для персонализации веб-страниц. Например, вы можете настроить передачу информации об имени подписчика и испо
пробел потерялся

2024-09-17 08:22 UTC, Ksksksksen commented on docs/other-channels/sms/how-to-create-sms-campaign.md
> +Если вы хотите убедиться, что сообщение будет отображаться именно так, как вы задумали, отправьте тестовую копию на свое устройство. Для этого укажите номер телефона и нажмите «Отправить».
своё

2024-09-17 08:22 UTC, Ksksksksen commented on docs/other-channels/web-push/how-to-create-web-push-campaign.md
> +Чтобы создать выпуск, зайдите в раздел **Рассылки → Выпуски**, нажмите «Создать выпуск» и выберите пункт **Web Push**.
в статье «как отправить email» тоже нужно внести правочку

2024-09-17 10:57 UTC, sendsay-cat approved these changes
Design awesome

2024-09-17 12:05 UTC, Lullabyq commented on docs/other-channels/sms/how-to-create-sms-campaign.md
> +import howToLimitAudience from "/img/other-channels/sms/how-to-create-sms-campaign/how-to-limit-audience.png";
лучше именовать файлы расширением mdx когда есть импорты

2024-09-18 10:40 UTC, Ksksksksen approved these changes

2024-09-18 11:04 UTC, Lullabyq approved these changes

2024-09-18 13:58 UTC, merged