fix(sendsay-docs) edit subscribers
sendsay-ru/sendsay-docs pull request #328
Opened 2024-10-01 08:35 UTC by vypolzovv

edit how-to-delete-contacts, what-is-list
[307](https://sendsay.fibery.io/%D0%90%D0%B2%D1%82%D0%BE%D1%80%D1%81%D0%BA%D0%B0%D1%8F/%D0%97%D0%B0%D0%B4%D0%B0%D1%87%D0%B8_%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%BE%D0%B2/307)

2024-10-01 09:10 UTC, Ksksksksen requested changes

2024-10-01 09:10 UTC, Ksksksksen commented on docs/subscribers/lists-and-segments/what-is-list.md
>  При подключении сайтов для пуш-рассылок и сообществ ВКонтакте автоматически создаются одноимённые списки, куда импортируются подписчики, — это нужно, чтобы отправлять рассылки подписчикам конкретного
давай сюда же в перечисление добавим про Telegram-ботов — там тоже создаётся список

2024-10-01 09:10 UTC, Ksksksksen commented on docs/subscribers/lists-and-segments/what-is-list.md
тут лишний абзац

2024-10-01 09:10 UTC, Ksksksksen commented on docs/subscribers/lists-and-segments/what-is-list.md
> +Если нажать «Удалить контакты из базы», контакты списка удалятся из базы. При этом список сохранится, но останется пустым. Пункт «Удалить список» удалит сам список, сохранив контакты в базе.
безвозвратно :)

2024-10-01 10:23 UTC, sendsay-cat approved these changes
Design awesome

2024-10-03 06:44 UTC, Lullabyq approved these changes

2024-10-03 07:12 UTC, merged